let products = [
    "apple iphone",
    "android",
    "blackberry z30",
    "bluetooth headset",
    "coconut oil",
    "coffee maker",
    "deodrants men",
    "deodrants women",
    "earphones",
    "electric scooter",
    "face wash",
    "firestick",
    "green tea",
    "gaming mouse",
    "hauwai mobiles",
    "headphones",
    "ipad",
    "iphone 12",
    "iphone 13",
    "iphone 12 pro",
    "jackets",
    "jbl",
    "kitchen accessories",
    "kent ro",
    "laptops",
    "laptops under 30000",
    "mobiles",
    "mobiles under 5000",
    "mobiles under 10000",
    "macbook",
    "mi tv",
    "macbook air",
    "mackbook pro",
    "microsoft surface",
    "noise earbuds",
    "narzo 50a",
    "nokia",
    "oppo watch",
    "oppo buds",
    "oppo",
    "oneplus 9t",
    "panasonic mobiles",
    "philips trimmer",
    "quaker oats",
    "quaker",
    "realme",
    "redme",
    "samsung flip",
    "sumsung mobiles",
    "smartwatch",
    "smartbulb",
    "smartphone",
    "techno spart",
    "toothpaste",
    "ups inverter",
    "us polo",
    "vivo v21",
    "vaseline",
    "watches",
    "xiomi redmi",
    "xbox controller",
    "yoga mat",
    "yoga bar",
    "z flip 3",
    "zebronics",
    "windows",
]